# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-05 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
